/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaPrincipal;

import Atividades.JInternalFrameInserir;
import Atividades.JInternalFrameAlterar;
import Atividades.JInternalFrameRemover;
import Atividades.JInternalFrameRelatoriosCategoria;
import Atividades.JInternalFrameRelatoriosData;

import Categorias.JInternalFrameInserir1;
import Categorias.JInternalFrameAlterar1;
import Categorias.JInternalFrameRemover1;
import Categorias.JInternalFrameRelatorios1;

import Ajuda.JInternalFrameSobre;

import javax.swing.JInternalFrame;

/**
 *
 * @author 029161041
 */
public class JFrameTelaPrincipal extends javax.swing.JFrame {
    //Atividades
    private JInternalFrameInserir jInternalFrameInserir;
    private JInternalFrameAlterar jInternalFrameAlterar;
    private JInternalFrameRemover jInternalFrameRemover;
    private JInternalFrameRelatoriosCategoria jInternalFrameRelatoriosCategoria;
    private JInternalFrameRelatoriosData jInternalFrameRelatoriosData;
    
    //Categorias
    private JInternalFrameInserir1 jInternalFrameInserir1;
    private JInternalFrameAlterar1 jInternalFrameAlterar1;
    private JInternalFrameRemover1 jInternalFrameRemover1;
    private JInternalFrameRelatorios1 jInternalFrameRelatorios1;
    
    //Ajuda
    private JInternalFrameSobre jInternalFrameSobre;

    /**
     * Creates new form JFrameTelaPrincipal
     */
    public JFrameTelaPrincipal() {
        initComponents();
        //Atividades
        jInternalFrameInserir = new JInternalFrameInserir();
        jInternalFrameAlterar = new JInternalFrameAlterar();
        jInternalFrameRemover = new JInternalFrameRemover();
        jInternalFrameRelatoriosCategoria = new JInternalFrameRelatoriosCategoria();
        jInternalFrameRelatoriosData = new JInternalFrameRelatoriosData();
        
        //Categorias
        jInternalFrameInserir1 = new JInternalFrameInserir1();
        jInternalFrameAlterar1 = new JInternalFrameAlterar1();
        jInternalFrameRemover1 = new JInternalFrameRemover1();
        jInternalFrameRelatorios1 = new JInternalFrameRelatorios1();
  
        //Ajuda
        jInternalFrameSobre = new JInternalFrameSobre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneTelaPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        atividadesInserir = new javax.swing.JMenuItem();
        atividadesAlterar = new javax.swing.JMenuItem();
        ativdadesRemover = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRelatorioCategoria = new javax.swing.JMenuItem();
        menuRelatorioData = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        categoriasInserir = new javax.swing.JMenuItem();
        categoriasAlterar = new javax.swing.JMenuItem();
        categoriasRemover = new javax.swing.JMenuItem();
        categoriasRelatorio = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        jDesktopPaneTelaPrincipal.setDoubleBuffered(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/21733140_1452124994869053_640976022_n.png"))); // NOI18N

        jDesktopPaneTelaPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneTelaPrincipalLayout = new javax.swing.GroupLayout(jDesktopPaneTelaPrincipal);
        jDesktopPaneTelaPrincipal.setLayout(jDesktopPaneTelaPrincipalLayout);
        jDesktopPaneTelaPrincipalLayout.setHorizontalGroup(
            jDesktopPaneTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneTelaPrincipalLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jDesktopPaneTelaPrincipalLayout.setVerticalGroup(
            jDesktopPaneTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );

        jMenu5.setText("Atividades");

        atividadesInserir.setText("Inserir");
        atividadesInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividadesInserirActionPerformed(evt);
            }
        });
        jMenu5.add(atividadesInserir);

        atividadesAlterar.setText("Alterar");
        atividadesAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividadesAlterarActionPerformed(evt);
            }
        });
        jMenu5.add(atividadesAlterar);

        ativdadesRemover.setText("Remover");
        ativdadesRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativdadesRemoverActionPerformed(evt);
            }
        });
        jMenu5.add(ativdadesRemover);

        jMenu2.setText("Relatórios");

        menuRelatorioCategoria.setText("Categorias");
        menuRelatorioCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(menuRelatorioCategoria);

        menuRelatorioData.setText("Data");
        menuRelatorioData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioDataActionPerformed(evt);
            }
        });
        jMenu2.add(menuRelatorioData);

        jMenu5.add(jMenu2);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Categorias");

        categoriasInserir.setText("Inserir");
        categoriasInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasInserirActionPerformed(evt);
            }
        });
        jMenu6.add(categoriasInserir);

        categoriasAlterar.setText("Alterar");
        categoriasAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasAlterarActionPerformed(evt);
            }
        });
        jMenu6.add(categoriasAlterar);

        categoriasRemover.setText("Remover");
        categoriasRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasRemoverActionPerformed(evt);
            }
        });
        jMenu6.add(categoriasRemover);

        categoriasRelatorio.setText("Relatórios");
        categoriasRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasRelatorioActionPerformed(evt);
            }
        });
        jMenu6.add(categoriasRelatorio);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar1.add(jMenu7);

        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneTelaPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneTelaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(852, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atividadesInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividadesInserirActionPerformed
        // TODO add your handling code here:

       if (jInternalFrameInserir.isVisible())
        {
            
            jInternalFrameInserir.moveToFront();   
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameInserir).setVisible(true);
        }
    }//GEN-LAST:event_atividadesInserirActionPerformed

    private void atividadesAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividadesAlterarActionPerformed
        // TODO add your handling code here:
        if (jInternalFrameAlterar.isVisible())
        {
            jInternalFrameAlterar.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameAlterar).setVisible(true);
        }
    }//GEN-LAST:event_atividadesAlterarActionPerformed

    private void ativdadesRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativdadesRemoverActionPerformed
        // TODO add your handling code here:
        if (jInternalFrameRemover.isVisible())
        {
            jInternalFrameRemover.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameRemover).setVisible(true);
        }
    }//GEN-LAST:event_ativdadesRemoverActionPerformed

    private void categoriasInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasInserirActionPerformed
        // TODO add your handling code here:
        if (jInternalFrameInserir1.isVisible())
        {
            jInternalFrameInserir1.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameInserir1).setVisible(true);
        }
    }//GEN-LAST:event_categoriasInserirActionPerformed

    private void categoriasAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasAlterarActionPerformed
        // TODO add your handling code here:
        if (jInternalFrameAlterar1.isVisible())
        {
            jInternalFrameAlterar1.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameAlterar1).setVisible(true);
        }
    }//GEN-LAST:event_categoriasAlterarActionPerformed

    private void categoriasRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasRemoverActionPerformed
        // TODO add your handling code here:
        if (jInternalFrameRemover1.isVisible())
        {
            jInternalFrameRemover1.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameRemover1).setVisible(true);
        }
    }//GEN-LAST:event_categoriasRemoverActionPerformed

    private void categoriasRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasRelatorioActionPerformed
        // TODO add your handling code here:
        if (jInternalFrameRelatorios1.isVisible())
        {
            jInternalFrameRelatorios1.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameRelatorios1).setVisible(true);
        }  
    }//GEN-LAST:event_categoriasRelatorioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          if (jInternalFrameSobre.isVisible())
        {
            jInternalFrameSobre.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameSobre).setVisible(true);
        }  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MousePressed

    private void menuRelatorioCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioCategoriaActionPerformed
        // TODO add your handling code here:
        if (jInternalFrameRelatoriosCategoria.isVisible())
        {
            jInternalFrameRelatoriosCategoria.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameRelatoriosCategoria).setVisible(true);
        }
    }//GEN-LAST:event_menuRelatorioCategoriaActionPerformed

    private void menuRelatorioDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioDataActionPerformed
        // TODO add your handling code here:
        if (jInternalFrameRelatoriosData.isVisible())
        {
            jInternalFrameRelatoriosData.moveToFront();
        }
        else
        {
            jDesktopPaneTelaPrincipal.add(jInternalFrameRelatoriosData).setVisible(true);
        }
    }//GEN-LAST:event_menuRelatorioDataActionPerformed
                                     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ativdadesRemover;
    private javax.swing.JMenuItem atividadesAlterar;
    private javax.swing.JMenuItem atividadesInserir;
    private javax.swing.JMenuItem categoriasAlterar;
    private javax.swing.JMenuItem categoriasInserir;
    private javax.swing.JMenuItem categoriasRelatorio;
    private javax.swing.JMenuItem categoriasRemover;
    private javax.swing.JDesktopPane jDesktopPaneTelaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuRelatorioCategoria;
    private javax.swing.JMenuItem menuRelatorioData;
    // End of variables declaration//GEN-END:variables
}
