/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Atividades;

import java.sql.Connection;
import javax.swing.JOptionPane;
import sqlite.SQLiteJDBCDriverConnection;

/**
 *
 * @author Admin
 */
public class JIFrameAtividadesAlterar extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameInserir
     */
    public JIFrameAtividadesAlterar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldAtividadesMatricula = new javax.swing.JTextField();
        jTextFieldAtividadesNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldAtividadesData = new javax.swing.JFormattedTextField();
        jLabelData = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jTextFieldAtividadesLocal = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jButtonAtividadesAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAtividadesDescricao = new javax.swing.JTextArea();
        jButtonLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alterar Atividades");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelMatricula.setText("Matrícula:");

        jLabelNome.setText("Nome:");

        try {
            jTextFieldAtividadesData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldAtividadesData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAtividadesDataActionPerformed(evt);
            }
        });

        jLabelData.setText("Data:");

        jLabelLocal.setText("Local:");

        jLabelDescricao.setText("Descrição:");

        jButtonAtividadesAlterar.setText("Alterar");
        jButtonAtividadesAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtividadesAlterarActionPerformed(evt);
            }
        });

        jTextAreaAtividadesDescricao.setColumns(20);
        jTextAreaAtividadesDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAtividadesDescricao);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAtividadesAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAtividadesNome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMatricula)
                                    .addComponent(jLabelData))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldAtividadesData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelLocal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAtividadesLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldAtividadesMatricula))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldAtividadesNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMatricula)
                    .addComponent(jTextFieldAtividadesMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAtividadesData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData)
                    .addComponent(jLabelLocal)
                    .addComponent(jTextFieldAtividadesLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescricao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonAtividadesAlterar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAtividadesDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAtividadesDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAtividadesDataActionPerformed

    private void jButtonAtividadesAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtividadesAlterarActionPerformed

        String matricula = jTextFieldAtividadesMatricula.getText();
       if (!(jTextFieldAtividadesMatricula.getText().equalsIgnoreCase("")) && !(jTextFieldAtividadesNome.getText().equalsIgnoreCase(""))
       && !(jTextFieldAtividadesData.getText().equalsIgnoreCase("  /  /    ")) && !(jTextFieldAtividadesLocal.getText().equalsIgnoreCase("")) 
       && !jTextAreaAtividadesDescricao.getText().equalsIgnoreCase("") ) {
        String nome = jTextFieldAtividadesNome.getText();
        String data = jTextFieldAtividadesData.getText();
        String local = jTextFieldAtividadesLocal.getText();
        String desc = jTextAreaAtividadesDescricao.getText();                      
           
        SQLiteJDBCDriverConnection bd = new SQLiteJDBCDriverConnection();
        Connection conn =  bd.connect();
        SQLiteJDBCDriverConnection.alteraDadosAtividade(conn, nome, data, local, desc, matricula);
        
        JOptionPane.showMessageDialog(null, "Atividade inserida com sucesso");
        
       jTextFieldAtividadesNome.requestFocus();
            
        jTextAreaAtividadesDescricao.setText(null);
        jTextFieldAtividadesData.setText(null);
        jTextFieldAtividadesLocal.setText(null);
        jTextFieldAtividadesMatricula.setText(null);
        jTextFieldAtividadesNome.setText(null);
       }else{
           JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
       }
    }//GEN-LAST:event_jButtonAtividadesAlterarActionPerformed
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        jTextAreaAtividadesDescricao.setText(null);
        jTextFieldAtividadesData.setText(null);
        jTextFieldAtividadesLocal.setText(null);
        jTextFieldAtividadesMatricula.setText(null);
        jTextFieldAtividadesNome.setText(null);
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextAreaAtividadesDescricao.setText(null);
        jTextFieldAtividadesData.setText(null);
        jTextFieldAtividadesLocal.setText(null);
        jTextFieldAtividadesMatricula.setText(null);
        jTextFieldAtividadesNome.setText(null);
    }//GEN-LAST:event_jButtonLimparActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtividadesAlterar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAtividadesDescricao;
    private javax.swing.JFormattedTextField jTextFieldAtividadesData;
    private javax.swing.JTextField jTextFieldAtividadesLocal;
    private javax.swing.JTextField jTextFieldAtividadesMatricula;
    private javax.swing.JTextField jTextFieldAtividadesNome;
    // End of variables declaration//GEN-END:variables
}
